sudo: false
cache:
    directories:
        - $HOME/.cache/pip
        - tests/bot-ci
addons:
    apt:
        packages:
            - libssl1.0.0
            - zsh
            - tcsh
            - mksh
            - busybox
            # - rc
            - socat
            - bc
            - libiw-dev
            - libasound2-dev
language: python
install: tests/install.sh
script:  echo "tests disabled" #tests/test.sh
matrix:
    include:
        - python: "3.4"
        - python: "3.5"
        - python: "3.6"

# vim: et
