sudo: false
cache:
    directories:
        - $HOME/.cache/pip
        - tests/bot-ci
addons:
    apt:
        packages:
            - libssl1.0.0
            - zsh
            - tcsh
            - mksh
            - busybox
            # - rc
            - socat
            - bc
            - libiw-dev
            - libasound2-dev
language: python
install: tests/install.sh
script: tests/test.sh
matrix:
    include:
        - python: "3.2"
        - python: "3.3"
        - python: "3.4"
        - python: "3.5"
        - python: "3.6"
        - python: "pypy3"
          env: >-
            USE_UCS2_PYTHON=1
            UCS2_PYTHON_VARIANT="2.7"

# vim: et
